---
- name: http_apache | Enable APC for php CLI
  ansible.builtin.lineinfile:
    dest: "{{ php_dir }}/mods-available/nc-cli_{{ nextcloud_instance_name }}.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
    mode: "0644"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  with_items:
    - {regexp: '; priority=', line: '; priority=50'}
    - {regexp: 'apc.enable_cli', line: 'apc.enable_cli=1'}
  notify:
    - Load php nc-cli module
    - Reload php-fpm

- name: http_apache | Enable PHP OPcache in nextcloud php module
  ansible.builtin.lineinfile:
    dest: "{{ php_dir }}/mods-available/nc_{{ nextcloud_instance_name }}.ini"
    state: present
    create: true
    mode: "0644"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '; priority=', line: '; priority=50'}
    - {regexp: 'opcache.enable=0', line: 'opcache.enable=1'}
    - {regexp: 'opcache.enable_cli', line: 'opcache.enable_cli=1'}
    - {regexp: 'opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer=16'}
    - {regexp: 'opcache.max_accelerated_files', line: 'opcache.max_accelerated_files=10000'}
    - {regexp: 'opcache.memory_consumption', line: 'opcache.memory_consumption=128'}
    - {regexp: 'opcache.save_comments', line: 'opcache.save_comments=1'}
    - {regexp: 'opcache.revalidate_freq', line: 'opcache.revalidate_freq=1'}
    - {regexp: '\bmemory_limit\b', line: 'memory_limit={{ php_memory_limit }}'}
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  notify:
    - Load php nc module
    - Reload php-fpm
    - Reload http

- name: http_apache | Enable required Apache2 modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - proxy_fcgi
    - setenvif
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: Restart http

- name: http_apache | Enable ssl Apache2 module
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
  when: (nextcloud_install_tls | bool)
  notify: Restart http

- name: http_apache | Enable Apache2 FPM configuration
  ansible.builtin.command:
    cmd: a2enconf php{{ php_ver }}-fpm
  register: fpm_conf
  changed_when: "'Enabling' in fpm_conf.stdout"
  notify: Restart http

- name: http_apache | Generate Nextcloud configuration for apache
  ansible.builtin.template:
    dest: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    src: "{{ nextcloud_websrv_template }}"
    mode: "0640"
  notify: Reload http

- name: http_apache | Enable Nextcloud site in apache conf
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/nc_{{ nextcloud_instance_name }}.conf
    src: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    state: link
  notify: Reload http

- name: http_apache | Disable apache default site
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  when: nextcloud_disable_websrv_default_site | bool
  notify: Reload http
