---
- name: php_install | Add external repository for PHP by using geerlingguy role
  ansible.builtin.import_role:
    name: geerlingguy.php-versions
  vars:
    php_version: "{{ php_ver }}"
  when: php_install_external_repos

- name: php_install | Install required PHP packages for Nextcloud
  ansible.builtin.package:
    name:
      - imagemagick
      - libmagickcore-*-extra
      - smbclient
      - "php{{ php_ver }}-fpm"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-ldap"
      - "php{{ php_ver }}-imap"
      - "php{{ php_ver }}-curl"
      - "php{{ php_ver }}-intl"
      - "php{{ php_ver }}-bz2"
    state: present

- name: "[php-fpm] - setup php nextcloud module"
  ansible.builtin.lineinfile:
    dest: "{{ php_dir }}/mods-available/nc_{{ nextcloud_instance_name }}.ini"
    state: present
    create: true
    mode: "0644"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '; priority=', line: '; priority=50'}
    - {regexp: 'opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer=16'}
    - {regexp: '\bmemory_limit\b', line: 'memory_limit={{ php_memory_limit }}'}
  notify:
    - Load php nc module
    - Start php-fpm
    - Reload http

- name: php_install | Install extra packages
  ansible.builtin.package:
    name: "{{ php_pkg_spe }}"
    state: present

- name: php_install | Install the php backend driver
  ansible.builtin.package:
    name: "php{{ php_ver }}-{{ db_driver }}{{ '*' if nextcloud_db_backend == 'sqlite' else '' }}"
    state: present
  vars:
    db_driver: "{{ (nextcloud_db_backend in ['mysql', 'mariadb'])|ternary('mysql', nextcloud_db_backend) }}"

- name: php_install | Install PHP APCu package
  ansible.builtin.package:
    name: "php{{ php_ver }}-apcu"
    state: present
