---

## Specific tasks after upgrading to NC 27

- name: Synchronize system addressbook
  become: true
  become_user: "{{ nextcloud_websrv_user }}"
  ansible.builtin.command: php occ -vvv dav:sync-system-addressbook
  args:
    chdir: "{{ nextcloud_webroot }}"
  changed_when: true

...
