---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Set parameter for a specific version of Nextcloud.
      ansible.builtin.set_fact:
        nextcloud_version_major: "{{ molecule_nc[2:] }}"
      when:
        - molecule_nc not in [ "", "latest" ]
        - molecule_nc is match("nc[0-9]{2,3}")
      vars:
        molecule_nc: "{{ lookup('env', 'MOLECULE_NC') }}"
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install gpg-agent
      ansible.builtin.package:
        name: gpg-agent
        state: present
      when: ansible_distribution == 'Ubuntu'
  vars:
    nextcloud_install_db: false
    nextcloud_db_name: nc
    nextcloud_db_admin: nc
    nextcloud_db_pwd: nc
    nextcloud_version_channel: "releases"
    nextcloud_get_latest: true
    nextcloud_apps:
      calendar:
      contacts:
        source: ""
        conf:
          var_1: "no"
      passwords:
    nextcloud_disable_apps:
      - photos
      - external
      - mail
  roles:
    - role: nextcloud.admin.install_nextcloud
