---
- name: Converge
  hosts: all
  become: true
  collections:
    - aalaesar.nextcloud
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: install_nextcloud
