---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    cgroupns_mode: host
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: "${MOLECULE_NC:-latest}-converge.yml"
verifier:
  name: ansible
