---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
  vars:
    nextcloud_version_channel: "releases"
    nextcloud_get_latest: true
    nextcloud_version_major: 25
    nextcloud_apps:
      calendar:
      contacts:
        source: "https://github.com/nextcloud-releases/contacts/releases/download/v5.0.2/contacts-v5.0.2.tar.gz"
        conf:
          var_1: "no"
      passwords:
    nextcloud_disable_apps:
      - photos
      - external
      - mail
  roles:
    - role: nextcloud.admin.install_nextcloud
