---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
  vars:
    nextcloud_install_db: false
    nextcloud_db_name: nc
    nextcloud_db_admin: nc
    nextcloud_db_pwd: nc
    nextcloud_version_channel: "releases"
    nextcloud_get_latest: true
    nextcloud_version_major: 28
    nextcloud_apps:
      calendar:
      contacts:
        source: ""
        conf:
          var_1: "no"
      passwords:
    nextcloud_disable_apps:
      - photos
      - external
      - mail
  roles:
    - role: nextcloud.admin.install_nextcloud
