---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    # load configurations references
    os_config_ref: "{{ lookup('ansible.builtin.template', '../../roles/install/defaults/os_config_ref.yml') | from_yaml }}"
  vars_files:
    - ../../roles/install/defaults/main.yml

  tasks:
    - name: "Include test_install"
      ansible.builtin.import_role:
        name: "test_install"
