---
# tasks file for upgrade

- name: Load distribution-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}_{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: Auto-detect current Nextcloud version
  ansible.builtin.include_tasks: current_version.yml
  when: nextcloud_initial_version is not defined

- name: Run pre-upgrade checks
  ansible.builtin.include_tasks: assert.yml

- name: Build `current_nextcloud_upgrade_path`
  ansible.builtin.set_fact:
    current_nextcloud_version: '{{ nextcloud_initial_version }}'
    current_nextcloud_upgrade_path: >-
      {{ nextcloud_upgrade_path
         | select('version', nextcloud_initial_version, '>')
         | select('version', nextcloud_target_version, '<=')
         | list }}

- name: See `current_nextcloud_upgrade_path`
  ansible.builtin.debug:
    var: current_nextcloud_upgrade_path
    verbosity: 2

- name: Loop upgrade step on `current_nextcloud_upgrade_path`
  ansible.builtin.include_tasks: upgrade_step.yml
  loop: '{{ current_nextcloud_upgrade_path }}'
  loop_control:
    loop_var: current_step_nextcloud_version
  when: current_nextcloud_upgrade_path | length > 0

...
