---
# Upgrade one step in the path, from `current_nextcloud_version` to `current_step_nextcloud_version`

# Check PHP version compatibility
- name: Run PHP version compatibility check
  ansible.builtin.include_tasks: php_version_check.yml

# Check PostgreSQL version compatibility
- name: Run PostgreSQL version compatibility check
  ansible.builtin.include_tasks: postgresql_version_check.yml
  when: not nextcloud_skip_postgresql

# Check Nextcloud version we are upgrading to
- name: Run version checks
  ansible.builtin.include_tasks: version_check.yml

- name: Execute upgrade operations for step {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: perform_upgrade.yml
  when: not _skip_upgrade_step | default(false)

- name: Display skip message
  ansible.builtin.debug:
    msg: >-
      Skipping upgrade execution for Nextcloud {{ current_step_nextcloud_version }}.
      {% if _nc_next_version == 'NO_UPDATE' -%}
      Update server reports no further updates available (might be a connectivity or upstream issue).
      {%- else -%}
      Update server reports next version is '{{ _nc_next_version }}'.
      {%- endif %}
  when: _skip_upgrade_step | default(false)
...
