---
# Upgrade one step in the path, from `current_nextcloud_version` to `current_step_nextcloud_version`

# Check Nextcloud version we are upgrading to
- name: Run version checks
  ansible.builtin.include_tasks: version_check.yml

# Check PHP version compatibility
- name: Run PHP version compatibility check
  ansible.builtin.include_tasks: php_version_check.yml
  when: not nextcloud_skip_php

# Check PostgreSQL version compatibility
- name: Run PostgreSQL version compatibility check
  ansible.builtin.include_tasks: postgresql_version_check.yml
  when: not nextcloud_skip_postgresql

# Tasks to run before the upgrade

- name: Specific tasks before upgrade to version {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - upgrade_tasks/pre_{{ current_step_nextcloud_version }}.yml
        - upgrade_tasks/pre_{{ step_version_members[0:2] | join('.') }}.yml
        - upgrade_tasks/pre_{{ step_version_members[0] | string }}.yml
      skip: true
  vars:
    step_version_members: "{{ current_step_nextcloud_version | ansible.builtin.split('.') }}"

# Upgrade step

- name: Run upgrade with maintenance mode
  become: true
  become_user: "{{ nextcloud_websrv_user }}"
  module_defaults:
    ansible.builtin.command:
      chdir: "{{ nextcloud_webroot }}"
  block:
    - name: Enable maintenance mode before upgrade
      ansible.builtin.command: php occ maintenance:mode --on
      changed_when: true

    - name: Upgrade Nextcloud to version {{ current_step_nextcloud_version }}
      ansible.builtin.command: "php {{ nextcloud_webroot }}/updater/updater.phar  --no-interaction"
      changed_when: true

    - name: Get Nextcloud status
      ansible.builtin.command: php occ status --output=json
      changed_when: false
      register: nextcloud_status

    - name: Verify Nextcloud version matches expected version
      ansible.builtin.assert:
        that:
          - (nextcloud_status.stdout | from_json).versionstring == current_step_nextcloud_version
        fail_msg: >-
          Nextcloud upgrade failed. Expected {{ current_step_nextcloud_version }}, but got {{ (nextcloud_status.stdout | from_json).versionstring }}.
        success_msg: "Nextcloud successfully upgraded to version {{ current_step_nextcloud_version }}."

    - name: Disable maintenance mode after upgrade
      ansible.builtin.command: php occ maintenance:mode --off
      changed_when: true

- name: Set current version to upgraded
  ansible.builtin.set_fact:
    current_nextcloud_version: '{{ current_step_nextcloud_version }}'

# Tasks to run after the upgrade

- name: Add missing indices
  become: true
  become_user: "{{ nextcloud_websrv_user }}"
  ansible.builtin.command: php occ -vvv db:add-missing-indices
  args:
    chdir: "{{ nextcloud_webroot }}"
  changed_when: true

- name: Specific tasks after upgrade to version {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - upgrade_tasks/post_{{ current_step_nextcloud_version }}.yml
        - upgrade_tasks/post_{{ step_version_members[0:2] | join('.') }}.yml
        - upgrade_tasks/post_{{ step_version_members[0] | string }}.yml
      skip: true
  vars:
    step_version_members: "{{ current_step_nextcloud_version | ansible.builtin.split('.') }}"

...
