---
# Upgrade one step in the path, from `current_nextcloud_version` to `current_step_nextcloud_version`

# Check PHP version compatibility
- name: Run PHP version compatibility check
  ansible.builtin.include_tasks: php_version_check.yml

# Check PostgreSQL version compatibility
- name: Run PostgreSQL version compatibility check
  ansible.builtin.include_tasks: postgresql_version_check.yml
  when: not nextcloud_skip_postgresql

# Check Nextcloud version we are upgrading to
- name: Run version checks
  ansible.builtin.include_tasks: version_check.yml

- name: Execute upgrade operations for step {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: perform_upgrade.yml
  when: not _skip_upgrade_step | default(false)

...
