---
- name: "[SIGNED TLS] - Define signed certificate-file with abolute path"
  ansible.builtin.set_fact:
    nextcloud_tls_cert_file: "{{ nextcloud_tls_cert_file | default(cert_path + nextcloud_instance_name + \".crt\") }}"

- name: "[SIGNED TLS] - Define signed certificate's key-file with absolute path"
  ansible.builtin.set_fact:
    nextcloud_tls_cert_key_file: "{{ nextcloud_tls_cert_key_file | default(cert_path + nextcloud_instance_name + \".key\") }}"

- name: "[SIGNED TLS] - Define certificate chain-file with absolute path"
  ansible.builtin.set_fact:
    nextcloud_tls_chain_file: "{{ nextcloud_tls_chain_file | default(cert_path + nextcloud_instance_name + \".pem\") }}"
  when: nextcloud_tls_src_chain is defined

- name: "[SIGNED TLS] - Copy certificate to the host"
  ansible.builtin.copy:
    dest: "{{ nextcloud_tls_cert_file }}"
    src: "{{ nextcloud_tls_src_cert }}"
    owner: "{{ nextcloud_websrv_user }}"
    group: "{{ nextcloud_websrv_group }}"
    mode: "0640"
    force: true
  when:
    - nextcloud_websrv not in ["nginx"]

- name: "[SIGNED TLS] - Copy and concatenate chained certificate file for nginx to host"
  ansible.builtin.template:
    src: templates/concatenate.j2
    dest: "{{ nextcloud_tls_cert_file }}"
    owner: "{{ nextcloud_websrv_user }}"
    group: "{{ nextcloud_websrv_group }}"
    mode: "0640"
  vars:
    input_files: ["{{ nextcloud_tls_src_cert }}", "{{ nextcloud_tls_src_chain }}"]
  when:
    - nextcloud_tls_src_chain is defined
    - nextcloud_websrv in ["nginx"]

- name: "[SIGNED TLS] - Key is copied to the host"
  ansible.builtin.copy:
    dest: "{{ nextcloud_tls_cert_key_file }}"
    src: "{{ nextcloud_tls_src_cert_key }}"
    owner: "{{ nextcloud_websrv_user }}"
    group: "{{ nextcloud_websrv_group }}"
    mode: "0400"
    force: false

- name: "[SIGNED TLS] - Certificate chain is copied to the host"
  ansible.builtin.copy:
    dest: "{{ nextcloud_tls_chain_file }}"
    src: "{{ nextcloud_tls_src_chain }}"
    owner: "{{ nextcloud_websrv_user }}"
    group: "{{ nextcloud_websrv_group }}"
    mode: "0640"
    force: false
  when: nextcloud_tls_src_chain is defined
