---
name: molecule tests
env:
  PYTHON_VERSION:  '3.12'
"on":
  workflow_call:
    inputs:
      distro:
        required: true
        description: a debian based distribution
        type: string
      nc_version:
        required: true
        description: a nextcloud server version
        type: string

defaults:
  run:
    working-directory: "nextcloud.ansible-collection-nextcloud-admin"

jobs:
  install_nextcloud:
    name: install_nextcloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          path: "nextcloud.ansible-collection-nextcloud-admin"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt ansible 'molecule-plugins[docker]' docker netaddr PyMySQL

      - name: precreate mysql database
        run: |
          sudo systemctl start mysql.service
          ansible localhost -m community.mysql.mysql_db -a "name=nc login_user=root login_password=root state=present"
          ansible localhost -m community.mysql.mysql_user -a "name=nc password=nc priv=nc.*:ALL login_user=root login_password=root state=present"

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ inputs.distro }}
          MOLECULE_NC: ${{ inputs.nc_version }}
