---
name: Pull Requests tests

on:
  pull_request:
    branches:
      - main

jobs:
  ansible_tests:
    name: plugins
    uses: ./.github/workflows/ansible-tests.yml

  molecule_tests:
    name: molecule-small
    uses: ./.github/workflows/molecule-tests.yml
    needs: ansible_tests
    strategy:
      matrix:
        distro: [debian12, ubuntu2404]
        nc_version: [latest]
    with:
      distro: ${{ matrix.distro }}
      nc_version: ${{ matrix.nc_version }}
